CREATE TABLE [raw].[ytVideoPerformanceReport] (
    [VideoPerfId]            INT           IDENTITY (1, 1) NOT NULL,
    [rptlogId]               BIGINT        NOT NULL,
    [rptdDate]               DATE          NOT NULL,
    [clientId]               BIGINT        NOT NULL,
    [AdGroupId]              VARCHAR (50)  NOT NULL,
    [AdGroupName]            VARCHAR (500) NULL,
    [AdGroupStatus]          VARCHAR (50)  NULL,
    [AdNetworkType1]         VARCHAR (50)  NULL,
    [AdNetworkType2]         VARCHAR (50)  NULL,
    [CampaignId]             VARCHAR (50)  NOT NULL,
    [CampaignName]           VARCHAR (500) NULL,
    [CampaignStatus]         VARCHAR (50)  NULL,
    [Clicks]                 VARCHAR (50)  NULL,
    [Conversions]            VARCHAR (50)  NULL,
    [ConversionValue]        VARCHAR (50)  NULL,
    [Cost]                   VARCHAR (50)  NULL,
    [CreativeId]             VARCHAR (50)  NOT NULL,
    [CreativeStatus]         VARCHAR (50)  NULL,
    [Date]                   VARCHAR (50)  NOT NULL,
    [Device]                 VARCHAR (50)  NOT NULL,
    [Engagements]            VARCHAR (50)  NULL,
    [Impressions]            VARCHAR (50)  NULL,
    [VideoChannelId]         VARCHAR (50)  NOT NULL,
    [VideoDuration]          VARCHAR (50)  NULL,
    [VideoId]                VARCHAR (50)  NULL,
    [VideoQuartile100Rate]   VARCHAR (50)  NULL,
    [VideoQuartile25Rate]    VARCHAR (50)  NULL,
    [VideoQuartile50Rate]    VARCHAR (50)  NULL,
    [VideoQuartile75Rate]    VARCHAR (50)  NULL,
    [VideoTitle]             VARCHAR (500) NULL,
    [VideoViews]             VARCHAR (50)  NULL,
    [ViewThroughConversions] VARCHAR (50)  NULL,
    CONSTRAINT [PK_VideoPerformanceReport] PRIMARY KEY CLUSTERED ([VideoPerfId] ASC)
);

