CREATE TABLE [dbo].[ReportLog] (
    [rptlogId]                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [rptqId]                     BIGINT        NOT NULL,
    [rptlogReportTypes]          INT           NOT NULL,
    [rptlogDequedOn]             DATETIME2 (7) CONSTRAINT [DF_ReportLog_rptlogDequedOn] DEFAULT (sysutcdatetime()) NOT NULL,
    [rptlogLastUpdatedOn]        DATETIME2 (7) CONSTRAINT [DF_ReportLog_rptqLastUpdatedOn] DEFAULT (sysutcdatetime()) NOT NULL,
    [rptlogCompletedOn]          DATETIME2 (7) NULL,
    [errlogId]                   BIGINT        NULL,
    [acctperfReportRequestedOn]  DATETIME2 (7) NULL,
    [acctperfDownloadedOn]       DATETIME2 (7) NULL,
    [acctperfDecompressedOn]     DATETIME2 (7) NULL,
    [acctperfLoadStartedOn]      DATETIME2 (7) NULL,
    [acctperfLoadCompletedOn]    DATETIME2 (7) NULL,
    [acctperfZeroImpressions]    BIT           NULL,
    [campperfReportRequestedOn]  DATETIME2 (7) NULL,
    [campperfDownloadedOn]       DATETIME2 (7) NULL,
    [campperfDecompressedOn]     DATETIME2 (7) NULL,
    [campperfLoadStartedOn]      DATETIME2 (7) NULL,
    [campperfLoadCompletedOn]    DATETIME2 (7) NULL,
    [adgrpperfReportRequestedOn] DATETIME2 (7) NULL,
    [adgrpperfDownloadedOn]      DATETIME2 (7) NULL,
    [adgrpperfDecompressedOn]    DATETIME2 (7) NULL,
    [adgrpperfLoadStartedOn]     DATETIME2 (7) NULL,
    [adgrpperfLoadCompletedOn]   DATETIME2 (7) NULL,
    [adperfReportRequestedOn]    DATETIME2 (7) NULL,
    [adperfDownloadedOn]         DATETIME2 (7) NULL,
    [adperfDecompressedOn]       DATETIME2 (7) NULL,
    [adperfLoadStartedOn]        DATETIME2 (7) NULL,
    [adperfLoadCompletedOn]      DATETIME2 (7) NULL,
    [kwperfReportRequestedOn]    DATETIME2 (7) NULL,
    [kwperfDownloadedOn]         DATETIME2 (7) NULL,
    [kwperfDecompressedOn]       DATETIME2 (7) NULL,
    [kwperfLoadStartedOn]        DATETIME2 (7) NULL,
    [kwperfLoadCompletedOn]      DATETIME2 (7) NULL,
    CONSTRAINT [PK_ReportLog] PRIMARY KEY CLUSTERED ([rptlogId] ASC),
    CONSTRAINT [CK_ReportLog_rptlogReportTypes] CHECK ([rptlogreporttypes]>=(1) AND [rptlogreporttypes]<=(255)),
    CONSTRAINT [FK_ReportLog_ErrorLog] FOREIGN KEY ([errlogId]) REFERENCES [dbo].[ErrorLog] ([errlogId]),
    CONSTRAINT [FK_ReportLog_ReportQueue] FOREIGN KEY ([rptqId]) REFERENCES [dbo].[ReportQueue] ([rptqId])
);



